function [ mfc ] = calc_mfcc(infile,outfile,varargin)
% calc_mfcc(infile, outfile)
%   Emulate HTK MFCC calculation as best as possible
% 2014-03-19 Louis Ranjard l.ranjard@auckland.ac.nz
% 2013-02-26 Dan Ellis dpwe@ee.columbia.edu


% Parse out the optional arguments
[wintime, hoptime, numcep, lifterexp, sumpower, preemph, dither, ...
 minfreq, maxfreq, nbands, bwidth, dcttype, fbtype, usecmp, modelorder, broaden] = ...
     process_options(varargin, 'wintime', 0.025, 'hoptime', 0.010, ...
          'numcep', 13, 'lifterexp', -22, 'sumpower', 1, 'preemph', 0.97, ...
	      'dither', 0, 'minfreq', 300, 'maxfreq', 20000, ...
	      'nbands', 26, 'bwidth', 1.0, 'dcttype', 3, ...
	      'fbtype', 'htkmel', 'usecmp', 0, 'modelorder', 0, 'broaden', 0);

      
[d,sr] = audioread(infile);
% This is how HTK sees the samples
d = (32768*d);

mfc = melfcc(d, sr, 'wintime', wintime, 'hoptime', hoptime,...
          'numcep', numcep, 'lifterexp', lifterexp, 'sumpower', sumpower,...
          'preemph', preemph, 'dither', dither, 'minfreq', minfreq,...
          'maxfreq', maxfreq, 'nbands', nbands, 'bwidth', bwidth,... 
          'dcttype', dcttype, 'fbtype', fbtype, 'usecmp', usecmp,...
          'modelorder', modelorder, 'broaden', broaden);
mfc = (mfc/2)';

if nargin>1 && exist('outfile','var') && ~isempty(outfile)  
    %writeasc(outfile, mfc');
    % use VOICEBOX writehtk() instead, use USER (tc=9) data format for HTK, required for reading the data later
     writehtk(outfile,mfc,hoptime,9);
end
